[package]
name = "scrypt-rs-wasm"
version = "0.1.0"
authors = ["Lars Hvam"]
edition = "2018"
rust-version = "1.76"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.92"
scrypt = { version = "0.2", default-features = false }
console_error_panic_hook = "0.1.7"